#!/usr/bin/env python3
"""gen_build_rev.py <out.h> -- write the build tag header (git short rev +
dirty flag + date) ONLY when its content changes, so the TUs that include it
(ui/menu.cpp and, on 3DS, rendering/renderer_c3d.cpp) recompile when the
revision moves and never otherwise. Both build systems run this every build
(Makefile FORCE rule / CMake custom target)."""
import subprocess, sys, os, datetime
out = sys.argv[1]
root = os.path.dirname(os.path.dirname(os.path.dirname(os.path.abspath(__file__))))
def git(*a):
    try: return subprocess.check_output(["git", "-C", root] + list(a), stderr=subprocess.DEVNULL).decode().strip()
    except Exception: return ""
rev = git("rev-parse", "--short", "HEAD") or "unknown"
dirty = "+" if git("status", "--porcelain", "--untracked-files=no") else ""
date = datetime.date.today().isoformat()
text = '// generated by t2k_core/tools/gen_build_rev.py -- do not edit\n#define T2K_BUILD_REV "%s%s"\n#define T2K_BUILD_DATE "%s"\n' % (rev, dirty, date)
os.makedirs(os.path.dirname(os.path.abspath(out)), exist_ok=True)
old = open(out).read() if os.path.exists(out) else None
if old != text:
    open(out, "w").write(text)
