#pragma once
// GENERATED by tools/gen_wordmark.py from the GAME'S OWN VECTOR FONT
// (src/rendering/font_data.cpp) -- do not hand-edit.
//
// The DEMO wordmark uses the same letterforms as every other string
// on screen. This header is GEOMETRY ONLY: the stroke weight is
// gen_logo.py's HALF_W, so the wordmarks are one family with the
// title, and the COLOURS belong to the consumer, not here -- they are
// the ICE neon stack in ui/demo_overlay.h. Its curves are deliberately
// not traced from artwork -- see tools/gen_logo.py's header for the
// decision and why.
//
// UNLIKE logo_data.h, a glyph here is a LIST OF CONTOURS: 'D' and 'O'
// enclose a counter. OUTLINE ONLY -- no face data is emitted and the
// Glyph struct has no field for it; callers stroke the rings.
//
// Coordinates: game y-UP, centred on the origin, full width exactly
// 2.0 units, so a caller places it with one scale.
//
// NB the generator emits this block as FIXED text written for
// gameover_data.h; the wording above was corrected by hand, so a
// re-run restores the stale version.
#include <array>

namespace ts {
namespace demowm {

struct Pt { float x, y; };
struct Contour { const Pt* pts; int n; };

// --- glyph 0 'D' (2 contour(s), 0 face pts, 0 tris) ---
inline constexpr std::array<Pt, 19> G0_C0 = {{
    {-0.997442f, 0.208882f},
    {-0.999986f, 0.197059f},
    {-1.000000f, -0.195745f},
    {-0.997442f, -0.208882f},
    {-0.989125f, -0.220706f},
    {-0.979471f, -0.226854f},
    {-0.967647f, -0.229397f},
    {-0.572216f, -0.229333f},
    {-0.560392f, -0.226274f},
    {-0.549882f, -0.218537f},
    {-0.543220f, -0.207569f},
    {-0.541178f, -0.195745f},
    {-0.543473f, -0.183922f},
    {-0.550071f, -0.173412f},
    {-0.944000f, 0.220517f},
    {-0.954510f, 0.227115f},
    {-0.967647f, 0.229397f},
    {-0.980784f, 0.226274f},
    {-0.991294f, 0.218537f},
}};
inline constexpr std::array<Pt, 3> G0_C1 = {{
    {-0.932176f, -0.162745f},
    {-0.656140f, -0.161588f},
    {-0.932714f, 0.114294f},
}};
inline constexpr std::array<Contour, 2> G0_CONTOURS = {{
    { G0_C0.data(), 19 },
    { G0_C1.data(), 3 },
}};

// --- glyph 1 'E' (1 contour(s), 0 face pts, 0 tris) ---
inline constexpr std::array<Pt, 42> G1_C0 = {{
    {-0.047980f, 0.226854f},
    {-0.061118f, 0.229412f},
    {-0.453922f, 0.229397f},
    {-0.465745f, 0.226854f},
    {-0.476255f, 0.219898f},
    {-0.483716f, 0.208882f},
    {-0.486275f, 0.195745f},
    {-0.486260f, -0.197059f},
    {-0.483716f, -0.208882f},
    {-0.476761f, -0.219392f},
    {-0.465745f, -0.226854f},
    {-0.452608f, -0.229412f},
    {-0.059804f, -0.229397f},
    {-0.047980f, -0.226854f},
    {-0.037471f, -0.219898f},
    {-0.031963f, -0.212824f},
    {-0.028317f, -0.203627f},
    {-0.027492f, -0.194431f},
    {-0.029264f, -0.185235f},
    {-0.039078f, -0.170784f},
    {-0.046667f, -0.165883f},
    {-0.055863f, -0.163111f},
    {-0.418451f, -0.162745f},
    {-0.418451f, -0.033333f},
    {-0.058490f, -0.033254f},
    {-0.046667f, -0.030196f},
    {-0.036157f, -0.022461f},
    {-0.029618f, -0.011824f},
    {-0.027451f, -0.000000f},
    {-0.029618f, 0.011824f},
    {-0.036157f, 0.022461f},
    {-0.046667f, 0.030196f},
    {-0.058490f, 0.033254f},
    {-0.418451f, 0.033333f},
    {-0.419608f, 0.161588f},
    {-0.055863f, 0.163111f},
    {-0.046667f, 0.165883f},
    {-0.039078f, 0.170784f},
    {-0.029264f, 0.185235f},
    {-0.028039f, 0.202314f},
    {-0.030902f, 0.210837f},
    {-0.036157f, 0.218537f},
}};
inline constexpr std::array<Contour, 1> G1_CONTOURS = {{
    { G1_C0.data(), 42 },
}};

// --- glyph 2 'M' (1 contour(s), 0 face pts, 0 tris) ---
inline constexpr std::array<Pt, 43> G2_C0 = {{
    {0.465745f, 0.226854f},
    {0.452608f, 0.229412f},
    {0.059804f, 0.229397f},
    {0.047980f, 0.226854f},
    {0.037471f, 0.219898f},
    {0.030009f, 0.208882f},
    {0.027451f, 0.195745f},
    {0.027465f, -0.197059f},
    {0.030009f, -0.208882f},
    {0.036965f, -0.219392f},
    {0.044039f, -0.224899f},
    {0.053235f, -0.228546f},
    {0.062431f, -0.229371f},
    {0.071627f, -0.227598f},
    {0.086078f, -0.217784f},
    {0.090979f, -0.210196f},
    {0.093752f, -0.201000f},
    {0.094118f, 0.161588f},
    {0.223529f, 0.161588f},
    {0.223608f, -0.198373f},
    {0.226667f, -0.210196f},
    {0.234401f, -0.220706f},
    {0.245039f, -0.227244f},
    {0.256863f, -0.229412f},
    {0.268686f, -0.227244f},
    {0.279324f, -0.220706f},
    {0.287059f, -0.210196f},
    {0.290117f, -0.198373f},
    {0.290196f, 0.161588f},
    {0.418451f, 0.162745f},
    {0.419973f, -0.201000f},
    {0.422746f, -0.210196f},
    {0.427647f, -0.217784f},
    {0.442098f, -0.227598f},
    {0.451294f, -0.229371f},
    {0.460490f, -0.228546f},
    {0.468373f, -0.225624f},
    {0.476255f, -0.219898f},
    {0.483716f, -0.208882f},
    {0.486275f, -0.195745f},
    {0.486260f, 0.197059f},
    {0.483716f, 0.208882f},
    {0.477569f, 0.218537f},
}};
inline constexpr std::array<Contour, 1> G2_CONTOURS = {{
    { G2_C0.data(), 43 },
}};

// --- glyph 3 'O' (2 contour(s), 0 face pts, 0 tris) ---
inline constexpr std::array<Pt, 20> G3_C0 = {{
    {0.979471f, 0.226854f},
    {0.966333f, 0.229412f},
    {0.573529f, 0.229397f},
    {0.561706f, 0.226854f},
    {0.551196f, 0.219898f},
    {0.543735f, 0.208882f},
    {0.541176f, 0.195745f},
    {0.541191f, -0.197059f},
    {0.543735f, -0.208882f},
    {0.550690f, -0.219392f},
    {0.561706f, -0.226854f},
    {0.574843f, -0.229412f},
    {0.967647f, -0.229397f},
    {0.979471f, -0.226854f},
    {0.989980f, -0.219898f},
    {0.997442f, -0.208882f},
    {1.000000f, -0.195745f},
    {0.999986f, 0.197059f},
    {0.997442f, 0.208882f},
    {0.991294f, 0.218537f},
}};
inline constexpr std::array<Pt, 4> G3_C1 = {{
    {0.932176f, -0.162745f},
    {0.933333f, 0.161588f},
    {0.609000f, 0.162745f},
    {0.607843f, -0.161588f},
}};
inline constexpr std::array<Contour, 2> G3_CONTOURS = {{
    { G3_C0.data(), 20 },
    { G3_C1.data(), 4 },
}};

struct Glyph {
    const Contour*        contours;
    int                   nContours;
};

inline constexpr int GLYPH_COUNT = 4;
inline constexpr std::array<Glyph, 4> GLYPHS = {{
    { G0_CONTOURS.data(), 2 },   // 'D'
    { G1_CONTOURS.data(), 1 },   // 'E'
    { G2_CONTOURS.data(), 1 },   // 'M'
    { G3_CONTOURS.data(), 2 },   // 'O'
}};

inline constexpr int   TOTAL_CONTOURS    = 6;
inline constexpr int   TOTAL_OUTLINE_PTS = 131;
inline constexpr float X_MIN = -1.000000f;
inline constexpr float X_MAX = 1.000000f;
inline constexpr float Y_MIN = -0.229412f;
inline constexpr float Y_MAX = 0.229412f;

} // namespace demowm
} // namespace ts
