#pragma once
// GENERATED by tools/gen_wordmark.py from the GAME'S OWN VECTOR FONT
// (src/rendering/font_data.cpp) -- do not hand-edit.
//
// This wordmark uses the same letterforms as every other string on
// screen: the generator PARSES the shipped font, so redrawing a glyph
// in font_data.cpp moves this artwork with it. COLOURS belong to the
// CONSUMER, not here. The curves are deliberately not traced from
// artwork -- see tools/gen_logo.py's header for the decision and why.
//
// UNLIKE logo_data.h, a glyph here is a LIST OF CONTOURS: letters
// with counters ('A', 'B', 'D', 'O', 'P', 'Q', 'R') come back with
// more than one, and 'R' additionally separates its LEG into a
// detached component at this stroke weight. Each contour is a closed
// ring to be stroked.
// OUTLINE ONLY -- no face data is emitted and the Glyph struct has
// no field for it; callers stroke the rings.
//
// Coordinates: game y-UP, centred on the origin, full width exactly
// 2.0 units, so a caller places it with one scale.
#include <array>

namespace ts {
namespace yeswm {

struct Pt { float x, y; };
struct Contour { const Pt* pts; int n; };

// --- glyph 0 'Y' (1 contour(s), 0 face pts, 0 tris) ---
inline constexpr std::array<Pt, 28> G0_C0 = {{
    {-0.992819f, 0.240426f},
    {-0.999841f, 0.225855f},
    {-1.000000f, 0.209826f},
    {-0.993371f, 0.195255f},
    {-0.783320f, -0.016028f},
    {-0.782359f, -0.225855f},
    {-0.774123f, -0.241883f},
    {-0.760919f, -0.251460f},
    {-0.743434f, -0.254338f},
    {-0.727405f, -0.249232f},
    {-0.715274f, -0.237512f},
    {-0.709464f, -0.220026f},
    {-0.709376f, -0.016028f},
    {-0.500479f, 0.193798f},
    {-0.494442f, 0.203998f},
    {-0.492041f, 0.214198f},
    {-0.492547f, 0.224397f},
    {-0.496096f, 0.234597f},
    {-0.505922f, 0.246471f},
    {-0.520493f, 0.253493f},
    {-0.536522f, 0.253652f},
    {-0.551093f, 0.247023f},
    {-0.746348f, 0.052286f},
    {-0.940146f, 0.245869f},
    {-0.950346f, 0.251906f},
    {-0.960545f, 0.254307f},
    {-0.970745f, 0.253801f},
    {-0.980945f, 0.250252f},
}};
inline constexpr std::array<Contour, 1> G0_CONTOURS = {{
    { G0_C0.data(), 28 },
}};

// --- glyph 1 'E' (1 contour(s), 0 face pts, 0 tris) ---
inline constexpr std::array<Pt, 42> G1_C0 = {{
    {0.055137f, 0.251616f},
    {0.040565f, 0.254453f},
    {-0.395115f, 0.254437f},
    {-0.408229f, 0.251616f},
    {-0.419886f, 0.243901f},
    {-0.428162f, 0.231683f},
    {-0.431000f, 0.217112f},
    {-0.430984f, -0.218569f},
    {-0.428162f, -0.231683f},
    {-0.420448f, -0.243340f},
    {-0.408229f, -0.251616f},
    {-0.393658f, -0.254453f},
    {0.042023f, -0.254437f},
    {0.055137f, -0.251616f},
    {0.066794f, -0.243901f},
    {0.072902f, -0.236054f},
    {0.076946f, -0.225855f},
    {0.077862f, -0.215655f},
    {0.075896f, -0.205455f},
    {0.065010f, -0.189426f},
    {0.056594f, -0.183991f},
    {0.046394f, -0.180915f},
    {-0.355773f, -0.180510f},
    {-0.355773f, -0.036972f},
    {0.043480f, -0.036884f},
    {0.056594f, -0.033492f},
    {0.068251f, -0.024913f},
    {0.075503f, -0.013114f},
    {0.077907f, -0.000000f},
    {0.075503f, 0.013114f},
    {0.068251f, 0.024913f},
    {0.056594f, 0.033492f},
    {0.043480f, 0.036884f},
    {-0.355773f, 0.036972f},
    {-0.357056f, 0.179227f},
    {0.046394f, 0.180915f},
    {0.056594f, 0.183991f},
    {0.065010f, 0.189426f},
    {0.075896f, 0.205455f},
    {0.077254f, 0.224397f},
    {0.074079f, 0.233851f},
    {0.068251f, 0.242392f},
}};
inline constexpr std::array<Contour, 1> G1_CONTOURS = {{
    { G1_C0.data(), 42 },
}};

// --- glyph 2 'S' (1 contour(s), 0 face pts, 0 tris) ---
inline constexpr std::array<Pt, 43> G2_C0 = {{
    {0.624938f, 0.251616f},
    {0.610367f, 0.254453f},
    {0.174686f, 0.254437f},
    {0.161572f, 0.251616f},
    {0.149915f, 0.243901f},
    {0.141639f, 0.231683f},
    {0.138802f, 0.217112f},
    {0.138831f, -0.001457f},
    {0.141796f, -0.014571f},
    {0.149719f, -0.026228f},
    {0.161572f, -0.034134f},
    {0.174686f, -0.036956f},
    {0.572482f, -0.036972f},
    {0.573765f, -0.179227f},
    {0.170315f, -0.180915f},
    {0.160115f, -0.183991f},
    {0.151699f, -0.189426f},
    {0.140813f, -0.205455f},
    {0.138847f, -0.215655f},
    {0.139763f, -0.225855f},
    {0.143004f, -0.234597f},
    {0.149354f, -0.243340f},
    {0.161572f, -0.251616f},
    {0.176143f, -0.254453f},
    {0.611824f, -0.254437f},
    {0.624938f, -0.251616f},
    {0.636595f, -0.243901f},
    {0.644871f, -0.231683f},
    {0.647709f, -0.217112f},
    {0.647680f, 0.001457f},
    {0.644715f, 0.014571f},
    {0.636792f, 0.026228f},
    {0.624938f, 0.034134f},
    {0.611824f, 0.036956f},
    {0.214029f, 0.036972f},
    {0.212746f, 0.179227f},
    {0.616196f, 0.180915f},
    {0.626395f, 0.183991f},
    {0.634812f, 0.189426f},
    {0.645697f, 0.205455f},
    {0.647056f, 0.224397f},
    {0.643881f, 0.233851f},
    {0.638052f, 0.242392f},
}};
inline constexpr std::array<Contour, 1> G2_CONTOURS = {{
    { G2_C0.data(), 43 },
}};

// --- glyph 3 '!' (2 contour(s), 0 face pts, 0 tris) ---
inline constexpr std::array<Pt, 18> G3_C0 = {{
    {0.953814f, 0.253279f},
    {0.939765f, 0.246193f},
    {0.929782f, 0.233586f},
    {0.926101f, 0.218569f},
    {0.926547f, -0.005829f},
    {0.930481f, -0.017486f},
    {0.938655f, -0.027775f},
    {0.949747f, -0.034492f},
    {0.962317f, -0.036964f},
    {0.976367f, -0.034492f},
    {0.988567f, -0.026756f},
    {0.996701f, -0.015314f},
    {1.000000f, -0.001457f},
    {0.999812f, 0.221483f},
    {0.996549f, 0.233140f},
    {0.990046f, 0.242744f},
    {0.980434f, 0.250114f},
    {0.969342f, 0.253915f},
}};
inline constexpr std::array<Pt, 16> G3_C1 = {{
    {0.930522f, -0.235032f},
    {0.939840f, -0.246254f},
    {0.952335f, -0.252864f},
    {0.966754f, -0.254268f},
    {0.980434f, -0.250114f},
    {0.991525f, -0.241065f},
    {0.998264f, -0.228769f},
    {0.999883f, -0.214198f},
    {0.995592f, -0.199929f},
    {0.986719f, -0.189076f},
    {0.973779f, -0.182099f},
    {0.959360f, -0.180695f},
    {0.945680f, -0.184849f},
    {0.934589f, -0.193894f},
    {0.927628f, -0.206912f},
    {0.926302f, -0.221483f},
}};
inline constexpr std::array<Contour, 2> G3_CONTOURS = {{
    { G3_C0.data(), 18 },
    { G3_C1.data(), 16 },
}};

struct Glyph {
    const Contour*        contours;
    int                   nContours;
};

inline constexpr int GLYPH_COUNT = 4;
inline constexpr std::array<Glyph, 4> GLYPHS = {{
    { G0_CONTOURS.data(), 1 },   // 'Y'
    { G1_CONTOURS.data(), 1 },   // 'E'
    { G2_CONTOURS.data(), 1 },   // 'S'
    { G3_CONTOURS.data(), 2 },   // '!'
}};

inline constexpr int   TOTAL_CONTOURS    = 5;
inline constexpr int   TOTAL_OUTLINE_PTS = 147;
inline constexpr float X_MIN = -1.000000f;
inline constexpr float X_MAX = 1.000000f;
inline constexpr float Y_MIN = -0.254453f;
inline constexpr float Y_MAX = 0.254453f;

} // namespace yeswm
} // namespace ts
