#!/usr/bin/env python3
"""spv2h.py — embed a compiled SPIR-V module as a C header.

    spv2h.py <in.spv> <out.h> <symbol>

Emits `static const uint32_t <symbol>[] = {...};` and
`static const size_t <symbol>_size` (BYTES). SPIR-V is a stream of 32-bit
words, so the array is uint32_t rather than bytes: vkCreateShaderModule
requires 4-byte alignment of pCode, and a uint32_t array gives it for free.

The header is regenerated by the build whenever the .spv changes (the CMake
custom command depends on it), so the same stale-header trap the port-docs
vault records for xxd-generated shader headers cannot happen here: the .spv
is itself a build product of the .glsl, and the header of the .spv.
"""
import sys, struct

def main():
    if len(sys.argv) != 4:
        sys.stderr.write(__doc__)
        return 2
    src, dst, sym = sys.argv[1:4]
    data = open(src, 'rb').read()
    if len(data) % 4 != 0 or len(data) < 20:
        sys.stderr.write(f"{src}: not a SPIR-V module (size {len(data)})\n")
        return 1
    magic = struct.unpack('<I', data[:4])[0]
    if magic != 0x07230203:
        sys.stderr.write(f"{src}: bad SPIR-V magic 0x{magic:08x}\n")
        return 1
    words = struct.unpack(f'<{len(data)//4}I', data)
    out = []
    out.append(f"// Generated by spv2h.py from {src.split('/')[-1]} -- do not edit.\n")
    out.append("#pragma once\n#include <stddef.h>\n#include <stdint.h>\n")
    out.append(f"static const uint32_t {sym}[] = {{\n")
    for i in range(0, len(words), 8):
        out.append("    " + ", ".join(f"0x{w:08x}" for w in words[i:i+8]) + ",\n")
    out.append("};\n")
    out.append(f"static const size_t {sym}_size = sizeof({sym});\n")
    open(dst, 'w').write("".join(out))
    return 0

if __name__ == '__main__':
    sys.exit(main())
