#!/usr/bin/env python3
"""build.py — rebuild the deployable soundtrack pool from the pinned map.

Reads `track_map.json` (generated by `build_map.py`, derived by byte-exact
encode match against the reference pool) and reproduces every deployable file:

    source FLAC --ffmpeg--> 32 kHz mono PCM16 --dspadpcm--> dsp/<name>.dsp
    mod/<src>.mod  --copy--> dsp/<deploy>.mod        (streams natively, no encode)

Each output is checked against the SHA-256 pinned in the map, so "correct file,
correct name, correct order" is proven rather than assumed. The album order the
game reads is taken from the map too, and written to `dsp/albums.json`.

Nothing here needs the reference pool: the map is the spec. The FLAC sources are
local-only (gitignored); `--fetch` pulls them from KHInsider.

    python3 build.py                # build + verify from local FLACs
    python3 build.py --fetch        # download missing FLACs first, then build
    python3 build.py --verify-only  # hash the existing pool against the map

Deps: ffmpeg on PATH; tools/bin/dspadpcm (built by tools/build_dspadpcm.sh).
"""
import argparse
import hashlib
import json
import os
import shutil
import subprocess
import sys

HERE = os.path.dirname(os.path.abspath(__file__))
ROOT = os.path.dirname(HERE)
DSP_DIR = os.path.join(HERE, "dsp")
MAP_PATH = os.path.join(HERE, "track_map.json")
ENCODER = os.path.join(ROOT, "tools", "bin", "dspadpcm")
RATE = 32000
# T2K_FORCE_REBUILD=1 (./build.sh --force) ignores the cached-output shortcut
# and re-encodes everything. Needed when the encoder or ffmpeg changes and you
# want to prove the pinned hashes still hold rather than trust the mtimes.
FORCE = bool(os.environ.get("T2K_FORCE_REBUILD"))
# The desktop/CIA staging pool. music_sdl.cpp resolves CWD-first and
# tools/stage_romfs.sh copies from here into the CIA's romfs/music.
STAGE_DIR = os.path.join(ROOT, "data", "music")
EMBEDDED_MANIFEST = os.path.join(ROOT, "t2k_core", "data", "albums_manifest.json")


def sha256(path):
    h = hashlib.sha256()
    with open(path, "rb") as f:
        for chunk in iter(lambda: f.read(1 << 20), b""):
            h.update(chunk)
    return h.hexdigest()


def ensure_encoder():
    if os.path.exists(ENCODER):
        return
    print("building vendored DSP encoder...")
    subprocess.run(["bash", os.path.join(ROOT, "tools", "build_dspadpcm.sh")], check=True)


def copy_into(src, dst):
    """Content-only copy, best-effort metadata.

    shutil.copy2's copystat tries to carry xattrs across, and on an NFS server
    that does not support the attribute set the whole call dies (EIO / errno 524
    on this tree) AFTER the bytes are already written. The bytes are the contract
    here — every copy is hash-checked against the pinned map — so metadata is
    explicitly not worth failing the build over.
    """
    shutil.copyfile(src, dst)
    try:
        shutil.copystat(src, dst)
    except OSError:
        pass


def encode_track(src_flac, out_dsp):
    wav = out_dsp + ".tmp.wav"
    try:
        subprocess.run(["ffmpeg", "-nostdin", "-v", "error", "-y", "-i", src_flac,
                        "-ac", "1", "-ar", str(RATE), wav], check=True)
        subprocess.run([ENCODER, wav, out_dsp], check=True,
                       stdout=subprocess.DEVNULL, stderr=subprocess.DEVNULL)
    finally:
        if os.path.exists(wav):
            os.remove(wav)


def build(fetch=False):
    if not os.path.exists(MAP_PATH):
        sys.exit(f"missing {MAP_PATH} — regenerate with soundtracks/build_map.py")
    m = json.load(open(MAP_PATH))
    ensure_encoder()
    os.makedirs(DSP_DIR, exist_ok=True)

    missing = [t for t in m["tracks"]
               if not os.path.exists(os.path.join(HERE, t["source"]["path"]))]
    if missing and fetch:
        slugs = sorted({t["source"]["slug"] for t in missing if t["source"].get("slug")})
        print(f"{len(missing)} source tracks missing — fetching "
              f"{len(slugs)} album(s) from KHInsider")
        subprocess.run([sys.executable, os.path.join(HERE, "download.py"),
                       "--no-convert", *sorted({t["source"]["folder"] for t in missing})],
                       check=False)
        missing = [t for t in m["tracks"]
                   if not os.path.exists(os.path.join(HERE, t["source"]["path"]))]
    if missing:
        print(f"{len(missing)} source tracks still missing. Run "
              f"`python3 soundtracks/download.py` (or pass --fetch).")
        for t in missing[:10]:
            print(f"  {t['dsp']}  <-  {t['source']['path']}")
        if len(missing) > 10:
            print(f"  ... and {len(missing) - 10} more")
        return 1

    built = cached = mismatched = 0
    for t in m["tracks"]:
        out = os.path.join(DSP_DIR, t["dsp"])
        src = os.path.join(HERE, t["source"]["path"])
        if not FORCE and os.path.exists(out) and sha256(out) == t["sha256"]:
            cached += 1
            continue
        encode_track(src, out)
        got = sha256(out)
        if got != t["sha256"]:
            # Not fatal: the pinned hash was produced by a specific ffmpeg
            # (swresample) build, so a different toolchain can legitimately
            # differ in the last bits. Duration is the contract that matters.
            print(f"  [hash differs] {t['dsp']}  expected {t['sha256'][:12]}…  "
                  f"got {got[:12]}…")
            mismatched += 1
        else:
            built += 1
            print(f"  {t['dsp']}")

    for d in m.get("mods", []):
        out = os.path.join(DSP_DIR, d["file"])
        src = os.path.join(HERE, d["source"]["path"])
        if not FORCE and os.path.exists(out) and sha256(out) == d["sha256"]:
            cached += 1
            continue
        copy_into(src, out)
        built += 1
        print(f"  {d['file']}  (copied from {d['source']['path']})")

    with open(os.path.join(DSP_DIR, "albums.json"), "w") as f:
        # indent=1 matches the committed file's style; a reformat here shows up
        # as a 115-line diff on a tracked file and hides real changes.
        # bonus_rounds rides along: it is not derivable from audio, and
        # build_map.py reads it back out of this file when it regenerates the
        # pinned map, so dropping it here would silently un-reserve the bonus
        # tracks the next time the map is rebuilt.
        json.dump({"albums": m["albums"],
                  "bonus_rounds": m.get("bonus_rounds", {})}, f, indent=1)

    print(f"\ndsp/: {built} built, {cached} already correct, {mismatched} hash-differs")
    print(f"wrote dsp/albums.json ({sum(len(v) for v in m['albums'].values())} "
          f"entries across {len(m['albums'])} albums)")
    check_embedded(m)
    return 0 if mismatched == 0 else 2


def check_embedded(m):
    """The CIA embeds t2k_core/data/albums_manifest.json as the fallback album
    map. If it drifts from the pinned map, a card with music but no albums.json
    beside it plays the wrong set — warn loudly rather than silently ship it."""
    if not os.path.exists(EMBEDDED_MANIFEST):
        print("[warn] embedded albums_manifest.json missing")
        return
    emb = json.load(open(EMBEDDED_MANIFEST))
    emb_albums = emb["albums"]
    pool = {t["dsp"] for t in m["tracks"]}
    problems = []
    for album, names in emb_albums.items():
        for n in names:
            if n.endswith(".dsp") and n not in pool:
                problems.append(f"{album}: {n} is not in the pinned pool")
    for album in m["albums"]:
        if album not in emb_albums:
            problems.append(f"{album}: in the map but not the embedded manifest")
    # The bonus-round reservation is the one thing here that changes what the
    # bonus rounds SOUND like, so it is compared as a whole rather than sampled.
    if emb.get("bonus_rounds", {}) != m.get("bonus_rounds", {}):
        problems.append(
            "bonus_rounds differs: map "
            f"{json.dumps(m.get('bonus_rounds', {}), sort_keys=True)} vs manifest "
            f"{json.dumps(emb.get('bonus_rounds', {}), sort_keys=True)}")
    if problems:
        print("[warn] embedded album map drifts from the pinned map:")
        for p in problems:
            print(f"    {p}")
        print("    regenerate: python3 t2k_core/tools/gen_albums.py")
    else:
        print("embedded album manifest consistent with the pinned map")


def verify_only():
    if not os.path.exists(MAP_PATH):
        sys.exit(f"missing {MAP_PATH}")
    m = json.load(open(MAP_PATH))
    bad = []
    for t in m["tracks"]:
        out = os.path.join(DSP_DIR, t["dsp"])
        if not os.path.exists(out):
            bad.append((t["dsp"], "missing"))
        elif sha256(out) != t["sha256"]:
            bad.append((t["dsp"], "hash mismatch"))
    for d in m.get("mods", []):
        out = os.path.join(DSP_DIR, d["file"])
        if not os.path.exists(out):
            bad.append((d["file"], "missing"))
        elif sha256(out) != d["sha256"]:
            bad.append((d["file"], "hash mismatch"))
    total = len(m["tracks"]) + len(m.get("mods", []))
    print(f"{total - len(bad)}/{total} deployable files match the pinned map")
    for n, why in bad:
        print(f"  {n}: {why}")
    return 1 if bad else 0


def main():
    ap = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    ap.add_argument("--fetch", action="store_true",
                    help="download missing source FLACs from KHInsider first")
    ap.add_argument("--verify-only", action="store_true",
                    help="hash the existing pool against the map, build nothing")
    ap.add_argument("--stage", action="store_true",
                    help="also refresh the repo-root data/music/ staging pool")
    args = ap.parse_args()

    rc = verify_only() if args.verify_only else build(args.fetch)

    if args.stage and rc != 1:
        os.makedirs(STAGE_DIR, exist_ok=True)
        n = 0
        for name in os.listdir(DSP_DIR):
            if name.endswith((".dsp", ".mod")):
                copy_into(os.path.join(DSP_DIR, name), os.path.join(STAGE_DIR, name))
                n += 1
        copy_into(os.path.join(DSP_DIR, "albums.json"),
                     os.path.join(STAGE_DIR, "albums.json"))
        print(f"staged {n} audio files + albums.json -> {STAGE_DIR}")
    sys.exit(rc)


if __name__ == "__main__":
    main()
