// ============================================================================
// renderer_vk.cpp — the render.h seam for the desktop, on Vulkan 1.3.
//
// Owns the device, the pipelines and the frame bracket; the passes live in
// vk_scene.cpp / vk_warp.cpp / vk_title.cpp / vk_post.cpp and the text seam
// in vk_font.cpp. See renderer_vk.h for the architecture.
//
// Presentation happens INSIDE the seam (ts_render_frame / *_end), exactly as
// the 3DS backend's C3D_FrameEnd does, so the frontend never touches a
// swapchain.
// ============================================================================

#include "renderer_vk.h"

#include <cmath>
#include <cstdio>
#include <cstring>
#include <new>

#include <glm/gtc/matrix_transform.hpp>
#include <volk.h>

#include "rendering/render.h"
#include "rendering/font.h"
#include "game/engine.h"
#include "game/camera.h"
#include "game/math_lut.h"
#include "game/phase.h"    // exact integer phase (cabinet uptime)

// Multiplier-wobble phase rate, Q0.48 turns/ms -- the parity twin of
// renderer_c3d.cpp's K_MULT_WOBBLE, same value, same law.
namespace { constexpr ts::phase::Rate K_MULT_WOBBLE = ts::phase::fromPiPerMs(0.00017); }
#include "game/fx_events.h"

// Embedded SPIR-V (generated by the build from shaders/*.{vert,frag}).
#include "shader_seg_vert.h"
#include "shader_seg_frag.h"
#include "shader_tri_vert.h"
#include "shader_tri_frag.h"
#include "shader_tri_tex_frag.h"
#include "shader_grid_vert.h"
#include "shader_grid_frag.h"
#include "shader_fullscreen_vert.h"
#include "shader_bloom_down_frag.h"
#include "shader_bloom_up_frag.h"
#include "shader_composite_frag.h"
#include "shader_river_vert.h"
#include "shader_river_frag.h"
#include "shader_star_vert.h"
#include "shader_texgen_frag.h"

namespace ts {
namespace vkr {

// ---- projection helpers (Vulkan clip conventions: y down, z in [0,1]) ------

// perspective(fovY, aspect, near, far) in the GAME's law (glm::perspective,
// right-handed, camera looks down -Z), then flipped for Vulkan's y-down NDC
// and remapped to the [0,1] depth range. Built by hand rather than through
// glm so no GLM_FORCE_* macro can differ between this TU and the core's.
static glm::mat4 perspectiveVk(float fovYDeg, float aspect, float n, float f) {
    const float t = std::tan(fovYDeg * 0.5f * 3.14159265358979f / 180.0f);
    glm::mat4 m(0.0f);
    m[0][0] = 1.0f / (aspect * t);
    m[1][1] = -1.0f / t;                 // y flip
    m[2][2] = f / (n - f);
    m[2][3] = -1.0f;
    m[3][2] = -(f * n) / (f - n);
    return m;
}

// The game's UI ortho box, 0..1.3333 x 0..1.0 with y UP, to Vulkan clip.
static glm::mat4 orthoUiVk() {
    glm::mat4 m(1.0f);
    m[0][0] = 2.0f / 1.3333f;  m[3][0] = -1.0f;
    m[1][1] = -2.0f;           m[3][1] = 1.0f;     // y up in UI, down in clip
    m[2][2] = 0.0f;            m[3][2] = 0.5f;     // z: constant, inside [0,1]
    return m;
}

glm::mat4 uiOrthoMatrix() { return orthoUiVk(); }

// The UI box on a seat-locked plane in stereo (UI_PLANE_DEPTH_M /
// UI_PLANE_HEIGHT_M): UI (x, y, z) -> seat-space (metres * units-per-metre),
// centred ahead of the seat, z of the UI vertex ignored exactly as the
// ortho box ignores it. Composed with the eye rig it becomes uiProj[v].
static glm::mat4 uiPlaneMatrix() {
    const float S = UI_PLANE_HEIGHT_M * XR_UNITS_PER_METRE;
    glm::mat4 m(0.0f);
    m[0][0] = S;
    m[1][1] = S;
    m[3][0] = -0.66665f * S;
    m[3][1] = -0.5f * S;
    m[3][2] = -UI_PLANE_DEPTH_M * XR_UNITS_PER_METRE;
    m[3][3] = 1.0f;
    return m;
}

// The game's VIEW law, identical on both existing backends (GL translateWorld
// / C3D buildView): multiplier wobble, game-over spiral, then the eye.
static glm::mat4 viewMatrix(const GameEngine& e) {
    glm::mat4 v(1.0f);
    const float PI = 3.14159265358979f;
    if (e.player.multiplier < 1.125f) {
        const float amp = 1.125f - e.player.multiplier;
        // Exact integer turns (game/phase.h) -- the parity twin of
        // renderer_c3d.cpp buildView. THIS is the build an arcade cabinet runs,
        // so it is the one that actually sits at multi-week uptimes where
        // `(float)e.time` stops resolving milliseconds and the whole view
        // matrix starts wobbling in visible steps.
        const float ang = ts::phase::sinTurns(ts::phase::at((uint32_t)e.time, K_MULT_WOBBLE))
                        * amp * amp * 60.0f;
        v = glm::rotate(v, glm::radians(ang), glm::vec3(0.1f, 0.1f, 1.0f));
    }
    if (e.player.gameover_animation > 10) {
        const float g = (e.player.gameover_animation - 10) * 0.01f;
        const float s = g * g;
        v = glm::scale(v, glm::vec3(1.0f - s * 0.25f, 1.0f - s * 0.25f, 1.0f + s));
        const float ang = ts::fastSin((float)(e.player.gameover_animation - 10) * PI * 0.0075f) * 120.0f;
        v = glm::rotate(v, glm::radians(ang), glm::vec3(0.1f, 0.1f, 1.0f));
    }
    const Vec3 eye = camera_eye(e);
    v = glm::translate(v, glm::vec3(-eye.x, -eye.y, -eye.z));
    return v;
}

// ---- descriptors -------------------------------------------------------------

VkDescriptorSet allocTexSet(Renderer& r, VkDescriptorSetLayout layout,
                            VkImageView v0, VkSampler s0, VkImageView v1, VkSampler s1) {
    VkDescriptorSetAllocateInfo ai{VK_STRUCTURE_TYPE_DESCRIPTOR_SET_ALLOCATE_INFO};
    ai.descriptorPool = r.descPool;
    ai.descriptorSetCount = 1;
    ai.pSetLayouts = &layout;
    VkDescriptorSet set = VK_NULL_HANDLE;
    if (vkAllocateDescriptorSets(r.ctx.device, &ai, &set) != VK_SUCCESS) {
        std::fprintf(stderr, "[vk] descriptor pool exhausted\n");
        return VK_NULL_HANDLE;
    }
    updateTexSet(r, set, v0, s0, v1, s1);
    return set;
}

void updateTexSet(Renderer& r, VkDescriptorSet set, VkImageView v0, VkSampler s0,
                  VkImageView v1, VkSampler s1) {
    VkDescriptorImageInfo ii[2]{};
    ii[0] = {s0, v0, VK_IMAGE_LAYOUT_GENERAL};
    ii[1] = {s1, v1, VK_IMAGE_LAYOUT_GENERAL};
    VkWriteDescriptorSet w[2]{};
    uint32_t n = 0;
    for (uint32_t i = 0; i < 2; ++i) {
        if (ii[i].imageView == VK_NULL_HANDLE) continue;
        w[n].sType = VK_STRUCTURE_TYPE_WRITE_DESCRIPTOR_SET;
        w[n].dstSet = set;
        w[n].dstBinding = i;
        w[n].descriptorCount = 1;
        w[n].descriptorType = VK_DESCRIPTOR_TYPE_COMBINED_IMAGE_SAMPLER;
        w[n].pImageInfo = &ii[i];
        ++n;
    }
    if (n) vkUpdateDescriptorSets(r.ctx.device, n, w, 0, nullptr);
}

void bindFrameSet(Renderer& r, VkPipelineLayout layout) {
    const uint32_t dyn = (uint32_t)r.frameUboOffset[r.ctx.frameIndex];
    vkCmdBindDescriptorSets(r.cmd, VK_PIPELINE_BIND_POINT_GRAPHICS, layout, 0, 1,
                            &r.frameSets[r.ctx.frameIndex], 1, &dyn);
}

// ---- pipelines ---------------------------------------------------------------

namespace {

bool createPipelines(Renderer& r) {
    vkctx::Context& c = r.ctx;
    Pipelines& p = r.pipes;

    // Set layouts.
    {
        VkDescriptorSetLayoutBinding b{0, VK_DESCRIPTOR_TYPE_UNIFORM_BUFFER_DYNAMIC, 1,
                                       VK_SHADER_STAGE_VERTEX_BIT | VK_SHADER_STAGE_FRAGMENT_BIT, nullptr};
        p.setFrame = vkpipe::createSetLayout(c, &b, 1);
        VkDescriptorSetLayoutBinding t1{0, VK_DESCRIPTOR_TYPE_COMBINED_IMAGE_SAMPLER, 1, VK_SHADER_STAGE_FRAGMENT_BIT, nullptr};
        p.setTex1 = vkpipe::createSetLayout(c, &t1, 1);
        VkDescriptorSetLayoutBinding t2[2] = {
            {0, VK_DESCRIPTOR_TYPE_COMBINED_IMAGE_SAMPLER, 1, VK_SHADER_STAGE_FRAGMENT_BIT, nullptr},
            {1, VK_DESCRIPTOR_TYPE_COMBINED_IMAGE_SAMPLER, 1, VK_SHADER_STAGE_FRAGMENT_BIT, nullptr}};
        p.setTex2 = vkpipe::createSetLayout(c, t2, 2);
        p.setPost = vkpipe::createSetLayout(c, t2, 2);
    }
    const VkShaderStageFlags VF = VK_SHADER_STAGE_VERTEX_BIT | VK_SHADER_STAGE_FRAGMENT_BIT;
    {
        VkDescriptorSetLayout s1[1] = {p.setFrame};
        VkDescriptorSetLayout sT1[2] = {p.setFrame, p.setTex1};
        VkDescriptorSetLayout sT2[2] = {p.setFrame, p.setTex2};
        p.layoutSeg    = vkpipe::createLayout(c, s1, 1, 0, 0);
        p.layoutStar   = vkpipe::createLayout(c, s1, 1, 64, VK_SHADER_STAGE_VERTEX_BIT);
        p.layoutTri    = vkpipe::createLayout(c, s1, 1, 16, VF);
        p.layoutTriTex = vkpipe::createLayout(c, sT1, 2, 16, VF);
        p.layoutGrid   = vkpipe::createLayout(c, sT2, 2, 32, VF);
        p.layoutRiver  = vkpipe::createLayout(c, sT2, 2, 16, VF);
        VkDescriptorSetLayout sP[1] = {p.setPost};
        p.layoutPost   = vkpipe::createLayout(c, sP, 1, 32, VK_SHADER_STAGE_FRAGMENT_BIT);
        p.layoutTexgen = vkpipe::createLayout(c, nullptr, 0, 32, VK_SHADER_STAGE_FRAGMENT_BIT);
    }

    // Shader modules.
    VkShaderModule segV = vkpipe::createShader(c, spv_seg_vert, spv_seg_vert_size);
    VkShaderModule segF = vkpipe::createShader(c, spv_seg_frag, spv_seg_frag_size);
    VkShaderModule triV = vkpipe::createShader(c, spv_tri_vert, spv_tri_vert_size);
    VkShaderModule triF = vkpipe::createShader(c, spv_tri_frag, spv_tri_frag_size);
    VkShaderModule triTexF = vkpipe::createShader(c, spv_tri_tex_frag, spv_tri_tex_frag_size);
    VkShaderModule gridV = vkpipe::createShader(c, spv_grid_vert, spv_grid_vert_size);
    VkShaderModule gridF = vkpipe::createShader(c, spv_grid_frag, spv_grid_frag_size);
    VkShaderModule fsV = vkpipe::createShader(c, spv_fullscreen_vert, spv_fullscreen_vert_size);
    VkShaderModule bdF = vkpipe::createShader(c, spv_bloom_down_frag, spv_bloom_down_frag_size);
    VkShaderModule buF = vkpipe::createShader(c, spv_bloom_up_frag, spv_bloom_up_frag_size);
    VkShaderModule compF = vkpipe::createShader(c, spv_composite_frag, spv_composite_frag_size);
    VkShaderModule riverV = vkpipe::createShader(c, spv_river_vert, spv_river_vert_size);
    VkShaderModule riverF = vkpipe::createShader(c, spv_river_frag, spv_river_frag_size);
    VkShaderModule starV = vkpipe::createShader(c, spv_star_vert, spv_star_vert_size);
    VkShaderModule texgenF = vkpipe::createShader(c, spv_texgen_frag, spv_texgen_frag_size);
    const VkShaderModule all[] = {segV, segF, triV, triF, triTexF, gridV, gridF, fsV, bdF, buF, compF, riverV, riverF, starV, texgenF};
    for (VkShaderModule m : all) if (m == VK_NULL_HANDLE) return false;

    // Vertex layouts.
    const vkpipe::VertexBinding segBind[] = {{0, sizeof(SegInst), true}};
    const vkpipe::VertexAttr segAttr[] = {
        {0, 0, VK_FORMAT_R32G32B32A32_SFLOAT, 0},
        {1, 0, VK_FORMAT_R32G32B32A32_SFLOAT, 16},
        {2, 0, VK_FORMAT_R32G32B32A32_SFLOAT, 32},
        {3, 0, VK_FORMAT_R32G32B32A32_SFLOAT, 48}};
    const vkpipe::VertexBinding starBind[] = {{0, sizeof(StarInst), true}};
    const vkpipe::VertexAttr starAttr[] = {
        {0, 0, VK_FORMAT_R32G32B32A32_SFLOAT, 0},
        {1, 0, VK_FORMAT_R32G32B32A32_SFLOAT, 16}};
    const vkpipe::VertexBinding triBind[] = {{0, sizeof(TriVert), false}};
    const vkpipe::VertexAttr triAttr[] = {
        {0, 0, VK_FORMAT_R32G32B32_SFLOAT, 0},
        {1, 0, VK_FORMAT_R32G32B32A32_SFLOAT, 12},
        {2, 0, VK_FORMAT_R32G32_SFLOAT, 28},
        {3, 0, VK_FORMAT_R32_UINT, 36}};
    const vkpipe::VertexBinding gridBind[] = {{0, sizeof(GridVert), false}};
    const vkpipe::VertexAttr gridAttr[] = {
        {0, 0, VK_FORMAT_R32G32B32_SFLOAT, 0},
        {1, 0, VK_FORMAT_R32G32_SFLOAT, 12},
        {2, 0, VK_FORMAT_R32G32_SFLOAT, 20},
        {3, 0, VK_FORMAT_R32G32B32_SFLOAT, 28},
        {4, 0, VK_FORMAT_R32G32_SFLOAT, 40},
        {5, 0, VK_FORMAT_R32G32_SFLOAT, 48}};
    const vkpipe::VertexBinding riverBind[] = {{0, sizeof(RiverVertVk), false}};
    const vkpipe::VertexAttr riverAttr[] = {
        {0, 0, VK_FORMAT_R32G32_SFLOAT, 0},
        {1, 0, VK_FORMAT_R32G32B32A32_SFLOAT, 8},
        {2, 0, VK_FORMAT_R32G32_SFLOAT, 24},
        {3, 0, VK_FORMAT_R32G32_SFLOAT, 32}};

    const VkFormat hdr[1] = {r.hdrFormat};
    auto sceneDesc = [&](VkShaderModule v, VkShaderModule f, VkPipelineLayout l, vkpipe::Blend b,
                         const vkpipe::VertexBinding* vb, uint32_t nb, const vkpipe::VertexAttr* va, uint32_t na,
                         VkPrimitiveTopology topo) {
        vkpipe::Desc d;
        d.vert = v; d.frag = f; d.layout = l; d.blend = b;
        d.bindings = vb; d.bindingCount = nb; d.attrs = va; d.attrCount = na;
        d.topology = topo;
        d.colorFormats = hdr; d.colorCount = 1;
        d.depthFormat = r.depthFormat;
        d.samples = r.sceneSamples;
        d.viewMask = r.viewMask;
        return d;
    };
    const auto STRIP = VK_PRIMITIVE_TOPOLOGY_TRIANGLE_STRIP;
    const auto LIST = VK_PRIMITIVE_TOPOLOGY_TRIANGLE_LIST;
    p.seg = vkpipe::createGraphics(c, sceneDesc(segV, segF, p.layoutSeg, vkpipe::BLEND_ADD, segBind, 1, segAttr, 4, STRIP));
    p.star = vkpipe::createGraphics(c, sceneDesc(starV, segF, p.layoutStar, vkpipe::BLEND_ADD, starBind, 1, starAttr, 2, STRIP));
    p.triAdd = vkpipe::createGraphics(c, sceneDesc(triV, triF, p.layoutTri, vkpipe::BLEND_ADD, triBind, 1, triAttr, 4, LIST));
    p.triAlpha = vkpipe::createGraphics(c, sceneDesc(triV, triF, p.layoutTri, vkpipe::BLEND_ALPHA, triBind, 1, triAttr, 4, LIST));
    p.triTexAdd = vkpipe::createGraphics(c, sceneDesc(triV, triTexF, p.layoutTriTex, vkpipe::BLEND_ADD, triBind, 1, triAttr, 4, LIST));
    p.triTexScreen = vkpipe::createGraphics(c, sceneDesc(triV, triTexF, p.layoutTriTex, vkpipe::BLEND_SCREEN_INV_DST, triBind, 1, triAttr, 4, LIST));
    p.gridTranslucent = vkpipe::createGraphics(c, sceneDesc(gridV, gridF, p.layoutGrid, vkpipe::BLEND_PREMUL, gridBind, 1, gridAttr, 6, LIST));
    p.gridOpaque = vkpipe::createGraphics(c, sceneDesc(gridV, gridF, p.layoutGrid, vkpipe::BLEND_NONE, gridBind, 1, gridAttr, 6, LIST));
    p.river = vkpipe::createGraphics(c, sceneDesc(riverV, riverF, p.layoutRiver, vkpipe::BLEND_PREMUL, riverBind, 1, riverAttr, 4, LIST));

    // Chamber pipelines: same shaders, single-sample HDR target, no depth.
    {
        const VkFormat chf[1] = {r.chamberFormat};
        auto chDesc = [&](VkShaderModule v, VkShaderModule f, VkPipelineLayout l, vkpipe::Blend b,
                          const vkpipe::VertexBinding* vb, uint32_t nb, const vkpipe::VertexAttr* va, uint32_t na,
                          VkPrimitiveTopology topo) {
            vkpipe::Desc d;
            d.vert = v; d.frag = f; d.layout = l; d.blend = b;
            d.bindings = vb; d.bindingCount = nb; d.attrs = va; d.attrCount = na;
            d.topology = topo;
            d.colorFormats = chf; d.colorCount = 1;
            d.depthFormat = VK_FORMAT_UNDEFINED;
            d.samples = VK_SAMPLE_COUNT_1_BIT;
            d.viewMask = 0;
            return d;
        };
        p.chamberMelt = vkpipe::createGraphics(c, chDesc(triV, triTexF, p.layoutTriTex, vkpipe::BLEND_NONE, triBind, 1, triAttr, 4, LIST));
        p.chamberInject = vkpipe::createGraphics(c, chDesc(segV, segF, p.layoutSeg, vkpipe::BLEND_ADD, segBind, 1, segAttr, 4, STRIP));
        p.chamberInjectTri = vkpipe::createGraphics(c, chDesc(triV, triF, p.layoutTri, vkpipe::BLEND_ADD, triBind, 1, triAttr, 4, LIST));
        p.chamberStar = vkpipe::createGraphics(c, chDesc(starV, segF, p.layoutStar, vkpipe::BLEND_ADD, starBind, 1, starAttr, 2, STRIP));
        // The composite of the chamber INTO the scene reuses triTexAdd.
        p.triTexReplace = p.chamberMelt;
    }

    // Post pipelines.
    {
        vkpipe::Desc d;
        d.vert = fsV; d.frag = bdF; d.layout = p.layoutPost; d.blend = vkpipe::BLEND_NONE;
        d.colorFormats = hdr; d.colorCount = 1;
        d.samples = VK_SAMPLE_COUNT_1_BIT;
        d.viewMask = r.viewMask;
        p.bloomDown = vkpipe::createGraphics(c, d);
        d.frag = buF; d.blend = vkpipe::BLEND_ADD;
        p.bloomUp = vkpipe::createGraphics(c, d);
        // Composite -> the swapchain format, single view (per-eye submits in VR
        // use compositeXr below).
        const VkFormat swf[1] = {c.headless ? r.hdrFormat : c.swapFormat};
        d.frag = compF; d.blend = vkpipe::BLEND_NONE;
        d.colorFormats = swf; d.viewMask = 0;
        p.composite = vkpipe::createGraphics(c, d);
        // Stereo composite: the same shader into the 2-layer target in ONE
        // multiview pass; the fragment reads layer gl_ViewIndex of scene and
        // bloom (composite.frag, layer override -1).
        if (r.viewCount > 1) {
            const VkFormat xrf[1] = {r.xrFormat};
            d.colorFormats = xrf; d.viewMask = r.viewMask;
            p.compositeXr = vkpipe::createGraphics(c, d);
            if (p.compositeXr == VK_NULL_HANDLE) return false;
        }
        // Texgen: MRT (A, B), no view mask.
        const VkFormat tgf[2] = {r.texgenFormat, r.texgenFormat};
        d.frag = texgenF; d.layout = p.layoutTexgen; d.blend = vkpipe::BLEND_NONE;
        d.colorFormats = tgf; d.colorCount = 2; d.viewMask = 0;
        p.texgen = vkpipe::createGraphics(c, d);
    }

    for (VkShaderModule m : all) vkDestroyShaderModule(c.device, m, nullptr);

    const VkPipeline check[] = {p.seg, p.star, p.triAdd, p.triAlpha, p.triTexAdd, p.triTexScreen,
                                p.gridTranslucent, p.gridOpaque, p.river, p.bloomDown, p.bloomUp,
                                p.composite, p.texgen, p.chamberMelt, p.chamberInject, p.chamberInjectTri,
                                p.chamberStar};
    for (VkPipeline q : check) if (q == VK_NULL_HANDLE) return false;
    return true;
}

void destroyPipelines(Renderer& r) {
    vkctx::Context& c = r.ctx;
    Pipelines& p = r.pipes;
    VkPipeline* ps[] = {&p.seg, &p.star, &p.triAdd, &p.triAlpha, &p.triTexAdd, &p.triTexScreen,
                        &p.gridTranslucent, &p.gridOpaque, &p.river, &p.bloomDown, &p.bloomUp,
                        &p.composite, &p.compositeXr, &p.texgen, &p.chamberMelt, &p.chamberInject, &p.chamberInjectTri,
                        &p.chamberStar};
    p.triTexReplace = VK_NULL_HANDLE;   // alias of chamberMelt
    for (VkPipeline* q : ps) { if (*q) vkDestroyPipeline(c.device, *q, nullptr); *q = VK_NULL_HANDLE; }
    VkPipelineLayout* ls[] = {&p.layoutSeg, &p.layoutStar, &p.layoutTri, &p.layoutTriTex, &p.layoutGrid,
                              &p.layoutRiver, &p.layoutPost, &p.layoutTexgen};
    for (VkPipelineLayout* l : ls) { if (*l) vkDestroyPipelineLayout(c.device, *l, nullptr); *l = VK_NULL_HANDLE; }
    VkDescriptorSetLayout* ss[] = {&p.setFrame, &p.setTex1, &p.setTex2, &p.setPost};
    for (VkDescriptorSetLayout* s : ss) { if (*s) vkDestroyDescriptorSetLayout(c.device, *s, nullptr); *s = VK_NULL_HANDLE; }
}

bool createStaticResources(Renderer& r) {
    vkctx::Context& c = r.ctx;

    r.sampLinearRepeat = vkres::createSampler(c, VK_FILTER_LINEAR, VK_SAMPLER_ADDRESS_MODE_REPEAT, false, 8.0f);
    r.sampLinearClamp = vkres::createSampler(c, VK_FILTER_LINEAR, VK_SAMPLER_ADDRESS_MODE_CLAMP_TO_EDGE, false);
    r.sampLinearClampMips = vkres::createSampler(c, VK_FILTER_LINEAR, VK_SAMPLER_ADDRESS_MODE_CLAMP_TO_EDGE, true);

    // Descriptor pool: a fixed budget, all sets live for the renderer's life.
    {
        VkDescriptorPoolSize sizes[2] = {
            {VK_DESCRIPTOR_TYPE_UNIFORM_BUFFER_DYNAMIC, 4},
            {VK_DESCRIPTOR_TYPE_COMBINED_IMAGE_SAMPLER, 160}};
        VkDescriptorPoolCreateInfo pci{VK_STRUCTURE_TYPE_DESCRIPTOR_POOL_CREATE_INFO};
        pci.maxSets = 96;
        pci.poolSizeCount = 2;
        pci.pPoolSizes = sizes;
        if (vkCreateDescriptorPool(c.device, &pci, nullptr, &r.descPool) != VK_SUCCESS) return false;
    }

    // Rings + frame sets (dynamic UBO over each frame's ring).
    for (int i = 0; i < vkctx::FRAMES_IN_FLIGHT; ++i) {
        if (!vkres::createRing(c, r.rings[i], RING_BYTES)) return false;
        VkDescriptorSetAllocateInfo ai{VK_STRUCTURE_TYPE_DESCRIPTOR_SET_ALLOCATE_INFO};
        ai.descriptorPool = r.descPool;
        ai.descriptorSetCount = 1;
        ai.pSetLayouts = &r.pipes.setFrame;
        if (vkAllocateDescriptorSets(c.device, &ai, &r.frameSets[i]) != VK_SUCCESS) return false;
        VkDescriptorBufferInfo bi{r.rings[i].buf.buf, 0, sizeof(FrameUBO)};
        VkWriteDescriptorSet w{VK_STRUCTURE_TYPE_WRITE_DESCRIPTOR_SET};
        w.dstSet = r.frameSets[i];
        w.dstBinding = 0;
        w.descriptorCount = 1;
        w.descriptorType = VK_DESCRIPTOR_TYPE_UNIFORM_BUFFER_DYNAMIC;
        w.pBufferInfo = &bi;
        vkUpdateDescriptorSets(c.device, 1, &w, 0, nullptr);
    }

    // 1x1 white and the 32x32 radial dot (the 3DS dotTex law: alpha = max(0, 1-dist)).
    {
        vkres::ImageDesc d; d.width = d.height = 1; d.format = VK_FORMAT_R8G8B8A8_UNORM;
        d.usage = VK_IMAGE_USAGE_SAMPLED_BIT | VK_IMAGE_USAGE_TRANSFER_DST_BIT;
        if (!vkres::createImage(c, r.whiteTex, d)) return false;
        const uint8_t white[4] = {255, 255, 255, 255};
        vkres::uploadImage(c, r.whiteTex, white, 4);
        r.whiteTex.layout = VK_IMAGE_LAYOUT_SHADER_READ_ONLY_OPTIMAL;
        d.width = d.height = 32;
        if (!vkres::createImage(c, r.dotTex, d)) return false;
        uint8_t dot[32 * 32 * 4];
        for (int y = 0; y < 32; ++y) for (int x = 0; x < 32; ++x) {
            const float dx = (x + 0.5f) / 16.0f - 1.0f, dy = (y + 0.5f) / 16.0f - 1.0f;
            const float dist = std::sqrt(dx * dx + dy * dy);
            const float a = dist < 1.0f ? 1.0f - dist : 0.0f;
            uint8_t* p = &dot[(y * 32 + x) * 4];
            p[0] = p[1] = p[2] = 255; p[3] = (uint8_t)(a * 255.0f + 0.5f);
        }
        vkres::uploadImage(c, r.dotTex, dot, sizeof(dot));
    }
    // Descriptor sets for the static textures. They were uploaded into
    // SHADER_READ_ONLY_OPTIMAL; the sets declare GENERAL, so transition.
    {
        VkCommandBuffer cmd = vkctx::beginOneShot(c);
        vkres::transition(cmd, r.whiteTex, VK_IMAGE_LAYOUT_GENERAL);
        vkres::transition(cmd, r.dotTex, VK_IMAGE_LAYOUT_GENERAL);
        vkctx::endOneShot(c, cmd);
    }
    r.whiteSet = allocTexSet(r, r.pipes.setTex1, r.whiteTex.view, r.sampLinearClamp);
    r.dotSet = allocTexSet(r, r.pipes.setTex1, r.dotTex.view, r.sampLinearClamp);

    // Texgen slots + the bonus sprite (generated once through the same pass).
    for (int i = 0; i < 2; ++i) if (!texgenEnsure(r, r.texgen[i])) return false;
    {
        vkres::ImageDesc d; d.width = d.height = 256; d.format = r.texgenFormat;
        d.usage = VK_IMAGE_USAGE_SAMPLED_BIT | VK_IMAGE_USAGE_COLOR_ATTACHMENT_BIT | VK_IMAGE_USAGE_TRANSFER_DST_BIT;
        if (!vkres::createImage(c, r.bonusTex, d)) return false;
        VkCommandBuffer cmd = vkctx::beginOneShot(c);
        vkres::transition(cmd, r.bonusTex, VK_IMAGE_LAYOUT_GENERAL);
        vkctx::endOneShot(c, cmd);
        r.bonusSet = allocTexSet(r, r.pipes.setTex1, r.bonusTex.view, r.sampLinearRepeat);
    }
    r.tex1.resize(GRID_VERTS_MAX * 2);
    r.tex2.resize(GRID_VERTS_MAX * 2);
    return true;
}

void destroyStaticResources(Renderer& r) {
    vkctx::Context& c = r.ctx;
    for (int i = 0; i < 2; ++i) { vkres::destroyImage(c, r.texgen[i].a); vkres::destroyImage(c, r.texgen[i].b); }
    vkres::destroyImage(c, r.bonusTex);
    vkres::destroyImage(c, r.dotTex);
    vkres::destroyImage(c, r.whiteTex);
    for (int i = 0; i < vkctx::FRAMES_IN_FLIGHT; ++i) vkres::destroyRing(c, r.rings[i]);
    if (r.descPool) { vkDestroyDescriptorPool(c.device, r.descPool, nullptr); r.descPool = VK_NULL_HANDLE; }
    if (r.sampLinearRepeat) vkDestroySampler(c.device, r.sampLinearRepeat, nullptr);
    if (r.sampLinearClamp) vkDestroySampler(c.device, r.sampLinearClamp, nullptr);
    if (r.sampLinearClampMips) vkDestroySampler(c.device, r.sampLinearClampMips, nullptr);
    r.sampLinearRepeat = r.sampLinearClamp = r.sampLinearClampMips = VK_NULL_HANDLE;
}

// The frame's UBO from the engine (or an identity world for UI-only frames).
void fillUbo(Renderer& r, const GameEngine* e) {
    FrameUBO& u = r.ubo;
    const float aspect = (float)r.width / (float)(r.height > 0 ? r.height : 1);
    float fov = tscam::FOV_Y_DEG;
    glm::mat4 view(1.0f);
    if (e) {
        if (e->fov_deg > 1.0f) fov = e->fov_deg;
        view = viewMatrix(*e);
    }
    const glm::mat4 proj = perspectiveVk(fov, aspect, 1.0f, 50.0f);
    const glm::mat4 ui = orthoUiVk();
    if (r.stereoMode == STEREO_HEADLESS) {
        // Synthetic rig: the game's FOV at the eye's aspect, eyes IPD apart.
        // eye-from-seat for the left eye translates by +ipd/2 (the eye sits
        // at -x in the seat), the right by -ipd/2.
        const float half = 0.5f * STEREO_DUMP_IPD_M * XR_UNITS_PER_METRE;
        for (int v = 0; v < MAX_VIEWS; ++v) {
            r.rigs[v].proj = proj;
            r.rigs[v].pose = glm::translate(glm::mat4(1.0f), glm::vec3(v == 0 ? half : -half, 0.0f, 0.0f));
        }
    }
    const bool stereo = r.stereoMode != STEREO_OFF;
    const glm::mat4 plane = uiPlaneMatrix();
    for (int v = 0; v < MAX_VIEWS; ++v) {
        if (stereo) {
            // The headset pose composes ON TOP of the game's camera: the seat
            // is camera_eye, the eyes are wherever the head is around it.
            u.proj[v] = r.rigs[v].proj;
            u.view[v] = r.rigs[v].pose * view;
            u.viewProj[v] = u.proj[v] * u.view[v];
            u.uiProj[v] = r.rigs[v].proj * r.rigs[v].pose * plane;
        } else {
            u.proj[v] = proj;
            u.view[v] = view;
            u.viewProj[v] = proj * view;
            u.uiProj[v] = ui;
        }
    }
    u.viewport = glm::vec4((float)r.width, (float)r.height, 1.0f / (float)r.width, 1.0f / (float)r.height);
    u.fog = glm::vec4(1.0f, 1.0f / (45.0f - 1.0f), 0.0f, 0.0f);   // FOG_START 1, FOG_END 45
    u.fogColor = e ? glm::vec4(e->bg_color[0], e->bg_color[1], e->bg_color[2], 1.0f) : glm::vec4(0.0f, 0.0f, 0.0f, 1.0f);
    const float pxScale = (float)r.height / 240.0f;
    float si = 1.0f;
    if (e) { si = e->shot_intensity; if (si < 0.25f) si = 0.25f; }
    const float timeS = e ? (float)e->time * 0.001f : 0.0f;
    u.params = glm::vec4(pxScale, timeS, si, 0.0f);
    // Phosphor halo: gain and reach (px at this resolution), thin-line floor.
    // Per-fragment phosphor halo on world segments: gain, reach (px). This is
    // the light that lives ON the line; the wide bleed is the bloom's job and
    // the web's own four-pass glow wire (WEB_GLOW_HALFPX) is the shared,
    // parity-bearing glow shape. So it is short and dim: 0.22 x 6*pxScale
    // (27 px reach at 1080p) on top of four glow passes was the fat-tube look.
    u.params2 = glm::vec4(0.10f, 2.0f * pxScale, 0.55f, 0.0f);
    // The web glow wire's shared four-pass shape, consumed as Gaussians by
    // SEG_GLOW (seg.frag). Same table the 3DS draws as nested quads.
    u.glowW = glm::vec4(WEB_GLOW_HALFPX[0], WEB_GLOW_HALFPX[1], WEB_GLOW_HALFPX[2], WEB_GLOW_HALFPX[3]);
    u.glowA = glm::vec4(WEB_GLOW_ALPHA[0], WEB_GLOW_ALPHA[1], WEB_GLOW_ALPHA[2], WEB_GLOW_ALPHA[3]);
    // The arcade enemy border's three-pass stack, halo passes at the shared
    // ARCADE_ENEMY_GLOW_HALO_SCALE (the emitter applies the same to the flat
    // passes the 3DS draws). The unused fourth slot has a non-zero width so
    // the shader's division stays finite, and zero alpha.
    u.glowW2 = glm::vec4(ARCADE_ENEMY_GLOW_HALFPX[0], ARCADE_ENEMY_GLOW_HALFPX[1], ARCADE_ENEMY_GLOW_HALFPX[2], 1.0f);
    u.glowA2 = glm::vec4(ARCADE_ENEMY_GLOW_ALPHA[0], ARCADE_ENEMY_GLOW_ALPHA[1] * ARCADE_ENEMY_GLOW_HALO_SCALE,
                         ARCADE_ENEMY_GLOW_ALPHA[2] * ARCADE_ENEMY_GLOW_HALO_SCALE, 0.0f);
}

} // namespace

void writeFrameUbo(Renderer& r) {
    VkDeviceSize off = 0;
    const VkDeviceSize align = r.ctx.props.limits.minUniformBufferOffsetAlignment > 64
                             ? r.ctx.props.limits.minUniformBufferOffsetAlignment : 64;
    void* p = vkres::ringAlloc(*r.ring, sizeof(FrameUBO), align, off);
    if (!p) return;
    std::memcpy(p, &r.ubo, sizeof(FrameUBO));
    r.frameUboOffset[r.ctx.frameIndex] = off;
}

// ---- create / destroy -----------------------------------------------------

// Arcade layout: target = min(4K, largest 16:9 inside the swapchain);
// outRect = largest centred 16:9 rect of the swapchain (the target is scaled
// onto it by the composite's linear sample when the display is not 4K).
void arcadeLayout(Renderer& r) {
    const uint32_t sw = r.ctx.swapExtent.width, sh = r.ctx.swapExtent.height;
    uint32_t ow = sw, oh = (sw * 9) / 16;
    if (oh > sh) { oh = sh; ow = (sh * 16) / 9; }
    r.outRect.offset = {(int32_t)((sw - ow) / 2), (int32_t)((sh - oh) / 2)};
    r.outRect.extent = {ow, oh};
    uint32_t tw = ARCADE_W, th = ARCADE_H;
    if (ow < tw) { tw = ow; th = oh; }
    r.width = tw; r.height = th;
}

bool rendererCreate(Renderer& r, SDL_Window* window, int width, int height, bool validation, bool arcade,
                    StereoMode stereo, int eyeW, int eyeH) {
    // Stereo outranks arcade: the eye targets are the headset's (or the
    // dump's), never the cabinet's fixed 16:9 4K.
    if (stereo != STEREO_OFF) arcade = false;
    // ---- OpenXR, phase 1: loader + instance + system, BEFORE Vulkan, because
    // the runtime creates the Vulkan objects. No loader / runtime / headset
    // is not an error: the reason is printed and the game runs flat.
    vkctx::XrVkHooks hooks;
    if (stereo == STEREO_XR) {
        r.xrSession = new (std::nothrow) xr::Session();
        xr::Desc xd;
        xd.validation = validation;
        if (!r.xrSession || !xr::createInstance(*r.xrSession, xd)) {
            if (r.xrSession) { xr::destroy(*r.xrSession); delete r.xrSession; r.xrSession = nullptr; }
            std::fprintf(stderr, "[xr] --xr requested but unavailable: running flat\n");
            stereo = STEREO_OFF;
        } else {
            hooks.user = r.xrSession;
            hooks.createInstance = xr::hookCreateVkInstance;
            hooks.pickPhysicalDevice = xr::hookPickVkPhysicalDevice;
            hooks.createDevice = xr::hookCreateVkDevice;
        }
    }
    vkctx::Desc d;
    d.window = window;
    d.validation = validation;
    // FIFO paces the flat game at the display's rate (arcade mode adds
    // present_wait on top). Under OpenXR the HEADSET paces the frame
    // (xrWaitFrame, 90 Hz); the window is a mirror, and a FIFO mirror on a
    // 60 Hz monitor would throttle the headset to 60. MAILBOX (uncapped,
    // latest-wins) when the driver has it; createSwapchain falls back to FIFO
    // where it does not.
    d.presentMode = stereo == STEREO_XR ? VK_PRESENT_MODE_MAILBOX_KHR : VK_PRESENT_MODE_FIFO_KHR;
    d.presentWait = arcade;
    if (stereo == STEREO_XR) d.xr = &hooks;
    if (!vkctx::create(r.ctx, d)) return false;
    r.arcade = arcade && !r.ctx.headless;
    if (r.arcade) arcadeLayout(r);
    else if (!r.ctx.headless) {
        r.width = r.ctx.swapExtent.width; r.height = r.ctx.swapExtent.height;
        r.outRect = {{0, 0}, r.ctx.swapExtent};
    } else { r.width = (uint32_t)width; r.height = (uint32_t)height; r.outRect = {{0, 0}, {r.width, r.height}}; }
    r.viewCount = 1;
    r.viewMask = 0;
    r.stereoMode = stereo;
    r.xrMode = stereo != STEREO_OFF;
    if (stereo == STEREO_XR) {
        // ---- phase 2: the session, its reference space and the 2-layer
        // swapchain on the finished device. The render size is the EYE's.
        const VkFormat pref[2] = {VK_FORMAT_R8G8B8A8_SRGB, VK_FORMAT_B8G8R8A8_SRGB};
        if (!xr::createSession(*r.xrSession, r.ctx.instance, r.ctx.phys, r.ctx.device,
                               r.ctx.queueFamily, 0, pref, 2)) return false;
        r.width = r.xrSession->eyeWidth;
        r.height = r.xrSession->eyeHeight;
        r.xrFormat = r.xrSession->swapFormat;
        r.xrViews.assign(r.xrSession->images.size(), VK_NULL_HANDLE);
        for (size_t i = 0; i < r.xrSession->images.size(); ++i) {
            VkImageViewCreateInfo vci{VK_STRUCTURE_TYPE_IMAGE_VIEW_CREATE_INFO};
            vci.image = r.xrSession->images[i];
            vci.viewType = VK_IMAGE_VIEW_TYPE_2D_ARRAY;
            vci.format = r.xrFormat;
            vci.subresourceRange = {VK_IMAGE_ASPECT_COLOR_BIT, 0, 1, 0, xr::VIEW_COUNT};
            if (vkCreateImageView(r.ctx.device, &vci, nullptr, &r.xrViews[i]) != VK_SUCCESS) return false;
        }
    } else if (stereo == STEREO_HEADLESS) {
        r.width = (uint32_t)(eyeW > 0 ? eyeW : 1024);
        r.height = (uint32_t)(eyeH > 0 ? eyeH : 1024);
        r.xrFormat = VK_FORMAT_R8G8B8A8_SRGB;
        vkres::ImageDesc id;
        id.width = r.width; id.height = r.height; id.layers = xr::VIEW_COUNT;
        id.format = r.xrFormat;
        id.usage = VK_IMAGE_USAGE_COLOR_ATTACHMENT_BIT | VK_IMAGE_USAGE_TRANSFER_SRC_BIT;
        if (!vkres::createImage(r.ctx, r.stereoDump, id)) return false;
    }
    if (stereo != STEREO_OFF) {
        if (r.ctx.maxMultiviewViews < xr::VIEW_COUNT) {
            std::fprintf(stderr, "[vk] device multiview count %u < 2\n", r.ctx.maxMultiviewViews);
            return false;
        }
        r.viewCount = xr::VIEW_COUNT;
        r.viewMask = 0b11;
        for (int v = 0; v < MAX_VIEWS; ++v) { r.rigs[v].proj = glm::mat4(1.0f); r.rigs[v].pose = glm::mat4(1.0f); }
    }
    // MSAA for the triangle edges (lines are SDF-antialiased regardless).
    {
        const VkSampleCountFlags ok = r.ctx.props.limits.framebufferColorSampleCounts & r.ctx.props.limits.framebufferDepthSampleCounts;
        r.sceneSamples = (ok & VK_SAMPLE_COUNT_4_BIT) ? VK_SAMPLE_COUNT_4_BIT : VK_SAMPLE_COUNT_1_BIT;
    }
    // Feedback-chamber storage: a NORMALIZED format when the device can blend
    // into one. The chamber's recurrence (rail_geometry.h FB_*) was tuned on
    // 8-bit targets, whose [0,1] clamp on every pass bounds the geometric
    // series; a float history has no such bound and the plume integrates
    // past white (vk_chamber.cpp, "THE STORAGE BOUND"). UNORM16 keeps the
    // clamp with a 1.5e-5 LSB, so the 8-bit residue sweep is still unneeded.
    {
        VkFormatProperties fp{};
        vkGetPhysicalDeviceFormatProperties(r.ctx.phys, VK_FORMAT_R16G16B16A16_UNORM, &fp);
        const VkFormatFeatureFlags need = VK_FORMAT_FEATURE_COLOR_ATTACHMENT_BLEND_BIT |
                                          VK_FORMAT_FEATURE_SAMPLED_IMAGE_FILTER_LINEAR_BIT;
        if ((fp.optimalTilingFeatures & need) == need) r.chamberFormat = VK_FORMAT_R16G16B16A16_UNORM;
    }
    if (!createPipelines(r)) return false;
    if (!createStaticResources(r)) return false;
    if (!postCreateTargets(r)) return false;
    r.starLastTime = 0.0;
    std::printf("[vk] renderer up: %ux%u%s, %s, MSAA x%d, texgen %u, chamber %u %s\n", r.width, r.height,
                r.viewCount > 1 ? " x2 views (multiview)" : "",
                r.stereoMode == STEREO_XR ? "openxr + mirror" : r.ctx.headless ? "headless" : "swapchain",
                (int)r.sceneSamples, TEXGEN_RES, CHAMBER_RES,
                r.chamberFormat == VK_FORMAT_R16G16B16A16_UNORM ? "unorm16" : "sfloat16");
    if (r.arcade)
        std::printf("[vk] arcade: fixed %ux%u target -> %ux%u output at (%d,%d) of a %ux%u swapchain, FIFO\n",
                    r.width, r.height, r.outRect.extent.width, r.outRect.extent.height,
                    r.outRect.offset.x, r.outRect.offset.y, r.ctx.swapExtent.width, r.ctx.swapExtent.height);
    return true;
}

void rendererDestroy(Renderer& r) {
    texMeanJoin();
    if (!r.ctx.device) return;
    vkctx::waitIdle(r.ctx);
    chamberDestroy(r, r.chamberTitle);
    chamberDestroy(r, r.chamberRail);
    chamberDestroy(r, r.chamberPause);
    chamberDestroy(r, r.chamberGameover);
    delete[] r.pauseSegBase; r.pauseSegBase = nullptr;
    delete[] r.pauseTriBase; r.pauseTriBase = nullptr;
    postDestroyTargets(r);
    destroyStaticResources(r);
    destroyPipelines(r);
    for (VkImageView v : r.xrViews) if (v) vkDestroyImageView(r.ctx.device, v, nullptr);
    r.xrViews.clear();
    vkres::destroyImage(r.ctx, r.stereoDump);
    // The session (and its swapchain images) goes before the device the
    // runtime created for it; the Vulkan objects are ours to destroy after.
    if (r.xrSession) { xr::destroy(*r.xrSession); delete r.xrSession; r.xrSession = nullptr; }
    vkctx::destroy(r.ctx);
}

// Re-size the targets after a swapchain recreate.
static bool handleResize(Renderer& r) {
    if (r.ctx.headless) return true;
    // In stereo the targets are the EYE's size; a mirror-window resize only
    // recreates the swapchain (vkctx does that) and the blit re-fits.
    if (r.stereoMode != STEREO_OFF) return true;
    if (r.arcade) {
        // Fixed target: only the output rect follows the swapchain; the
        // targets are rebuilt only if the display got too small for them.
        const uint32_t ow = r.width, oh = r.height;
        arcadeLayout(r);
        if (ow == r.width && oh == r.height) return true;
        vkctx::waitIdle(r.ctx);
        return postCreateTargets(r);
    }
    if (r.ctx.swapExtent.width == r.width && r.ctx.swapExtent.height == r.height) return true;
    vkctx::waitIdle(r.ctx);
    r.width = r.ctx.swapExtent.width;
    r.height = r.ctx.swapExtent.height;
    r.outRect = {{0, 0}, r.ctx.swapExtent};
    return postCreateTargets(r);
}

// ---- the frame bracket -------------------------------------------------------

bool frameBegin(Renderer& r, const GameEngine* engine, bool uiOnly) {
    (void)uiOnly;
    if (r.frameOpen) return true;
    // OpenXR paces the frame: events, then xrWaitFrame blocks to the
    // headset's display rate, then both views are located for the predicted
    // display time. A session that is not running (headset off, app in the
    // background) renders nothing and the loop keeps ticking.
    r.xrFrameOpen = false;
    if (r.stereoMode == STEREO_XR && r.xrSession) {
        xr::Session& s = *r.xrSession;
        xr::pollEvents(s);
        if (!xr::beginFrame(s)) {
            if (s.frameOpen) xr::endFrame(s, false);   // shouldRender == false: keep the pairing
            return false;
        }
        r.xrFrameOpen = true;
        for (uint32_t v = 0; v < xr::VIEW_COUNT; ++v) {
            xr::projectionFromFov(s.views[v].fov, 1.0f, 50.0f, &r.rigs[v].proj[0][0]);
            xr::viewFromPose(s.views[v].pose, XR_UNITS_PER_METRE, &r.rigs[v].pose[0][0]);
        }
    }
    VkCommandBuffer cmd = VK_NULL_HANDLE;
    // A minimised window or an out-of-date swapchain skips frames until the
    // swapchain is back; the game loop keeps ticking.
    bool ok = false;
    for (int attempt = 0; attempt < 2; ++attempt) {
        if (vkctx::beginFrame(r.ctx, cmd)) { ok = true; break; }
    }
    if (ok) ok = handleResize(r);
    if (!ok) {
        if (r.xrFrameOpen && r.xrSession) { xr::endFrame(*r.xrSession, false); r.xrFrameOpen = false; }
        return false;
    }
    r.cmd = cmd;
    r.ring = &r.rings[r.ctx.frameIndex];
    vkres::ringReset(*r.ring);
    fillUbo(r, engine);
    writeFrameUbo(r);
    r.frameOpen = true;
    r.sceneOpen = false;
    ++r.frameCounter;
    return true;
}

void sceneBegin(Renderer& r, const float clear[4]) {
    if (!r.frameOpen || r.sceneOpen) return;
    VkCommandBuffer cmd = r.cmd;
    const bool msaa = r.sceneSamples != VK_SAMPLE_COUNT_1_BIT;

    VkRenderingAttachmentInfo col{VK_STRUCTURE_TYPE_RENDERING_ATTACHMENT_INFO};
    col.imageView = msaa ? r.sceneMs.view : r.scene.view;
    col.imageLayout = msaa ? VK_IMAGE_LAYOUT_COLOR_ATTACHMENT_OPTIMAL : VK_IMAGE_LAYOUT_GENERAL;
    col.loadOp = VK_ATTACHMENT_LOAD_OP_CLEAR;
    col.storeOp = msaa ? VK_ATTACHMENT_STORE_OP_DONT_CARE : VK_ATTACHMENT_STORE_OP_STORE;
    for (int i = 0; i < 4; ++i) col.clearValue.color.float32[i] = clear[i];
    if (msaa) {
        col.resolveMode = VK_RESOLVE_MODE_AVERAGE_BIT;
        col.resolveImageView = r.scene.view;
        col.resolveImageLayout = VK_IMAGE_LAYOUT_GENERAL;
    }
    VkRenderingAttachmentInfo dep{VK_STRUCTURE_TYPE_RENDERING_ATTACHMENT_INFO};
    dep.imageView = r.sceneDepth.view;
    dep.imageLayout = VK_IMAGE_LAYOUT_DEPTH_ATTACHMENT_OPTIMAL;
    dep.loadOp = VK_ATTACHMENT_LOAD_OP_CLEAR;
    dep.storeOp = VK_ATTACHMENT_STORE_OP_DONT_CARE;
    dep.clearValue.depthStencil = {1.0f, 0};

    VkRenderingInfo ri{VK_STRUCTURE_TYPE_RENDERING_INFO};
    ri.renderArea = {{0, 0}, {r.width, r.height}};
    ri.layerCount = r.viewMask ? 1 : r.viewCount;
    ri.viewMask = r.viewMask;
    ri.colorAttachmentCount = 1;
    ri.pColorAttachments = &col;
    ri.pDepthAttachment = &dep;
    vkCmdBeginRendering(cmd, &ri);
    r.sceneOpen = true;
}

void sceneEnd(Renderer& r) {
    if (!r.sceneOpen) return;
    vkCmdEndRendering(r.cmd);
    r.sceneOpen = false;
}

void frameEnd(Renderer& r, float flashEnv, const float flashRgb[3]) {
    if (!r.frameOpen) return;
    sceneEnd(r);
    postRun(r, flashEnv, flashRgb, r.fade);
    vkctx::endFrame(r.ctx);
    // The headset's image is released AFTER the submit that wrote it, then
    // the projection layer (both views) goes to the compositor.
    if (r.xrFrameOpen && r.xrSession) { xr::endFrame(*r.xrSession, true); r.xrFrameOpen = false; }
    r.frameOpen = false;
    r.cmd = VK_NULL_HANDLE;
    r.ring = nullptr;
}

} // namespace vkr
} // namespace ts

// ============================================================================
// The render.h seam.
// ============================================================================

using namespace ts;
using namespace ts::vkr;

namespace {

Renderer* asRenderer(TsRenderer r) { return static_cast<Renderer*>(r); }

// The window the frontend created (SDL_WINDOW_VULKAN). Set by main.cpp
// through ts_render_set_window before ts_render_create.
SDL_Window* g_window = nullptr;
bool g_validation = false;
bool g_arcade = false;
// The stereo request (ts_render_set_stereo), consumed by ts_render_create.
StereoMode g_stereo = STEREO_OFF;
int g_eyeW = 0, g_eyeH = 0;

const float UI_CLEAR[4] = {0.02f, 0.02f, 0.05f, 1.0f};
const float BLACK[4] = {0.0f, 0.0f, 0.0f, 1.0f};

// Flush the UI batch: textured span first (level-select skin / logo), then
// everything else, then the glyph strokes on top. Same order text_c3d.cpp
// draws its batch in.
void flushUi(Renderer& r) {
    const int texEnd = r.uiTexturedSpanEnd >= 0 ? r.uiTexturedSpanEnd : r.uiTris.count;
    VkDescriptorSet texSet = r.whiteSet;
    if (r.uiTubeTexLevel >= 0 && r.texgen[1].setA != VK_NULL_HANDLE) texSet = r.texgen[1].setA;
    if (texEnd > 0)
        triStreamDraw(r, r.pipes.triTexAdd, r.pipes.layoutTriTex, r.uiTris, 0, texEnd, false, false, 1.0f, texSet);
    if (r.uiTris.count > texEnd)
        triStreamDraw(r, r.pipes.triTexAdd, r.pipes.layoutTriTex, r.uiTris, texEnd, r.uiTris.count - texEnd, false, false, 1.0f, r.whiteSet);
    segStreamDraw(r, r.uiSegs, 0, r.uiSegs.count, false);
}

void uiBegin(Renderer& r, const float clear[4]) {
    sceneBegin(r, clear);
    segStreamBegin(r, r.uiSegs, 32768);
    triStreamBegin(r, r.uiTris, 65536);
    r.uiTexturedSpanEnd = -1;
    r.uiOpen = true;
    fontSetTarget(&r, &r.uiSegs, &r.uiTris);
}

void uiEnd(Renderer& r) {
    if (!r.uiOpen) return;
    flushUi(r);
    fontSetTarget(nullptr, nullptr, nullptr);
    r.uiOpen = false;
    r.uiTubeTexLevel = -1;
}

} // namespace

void ts_render_set_window(SDL_Window* window, bool validation) {
    g_window = window;
    g_validation = validation;
}

void ts_render_set_arcade(bool arcade) {
    g_arcade = arcade;
}

void ts_render_set_stereo(int mode, int eyeW, int eyeH) {
    g_stereo = mode == 1 ? STEREO_XR : mode == 2 ? STEREO_HEADLESS : STEREO_OFF;
    g_eyeW = eyeW; g_eyeH = eyeH;
}

bool ts_render_stereo_active(TsRenderer rr) {
    Renderer* r = asRenderer(rr);
    return r && r->stereoMode != STEREO_OFF;
}

bool ts_render_xr_exit_requested(TsRenderer rr) {
    Renderer* r = asRenderer(rr);
    return r && r->xrSession && r->xrSession->exitRequested;
}

bool ts_render_stereo_dump(TsRenderer rr, const char* path) {
    Renderer* r = asRenderer(rr);
    return r && stereoDumpWrite(*r, path);
}

TsRenderer ts_render_create(int width, int height) {
    Renderer* r = new (std::nothrow) Renderer();
    if (!r) return nullptr;
    if (!rendererCreate(*r, g_window, width, height, g_validation, g_arcade, g_stereo, g_eyeW, g_eyeH)) {
        rendererDestroy(*r);
        delete r;
        return nullptr;
    }
    return r;
}

void ts_render_destroy(TsRenderer rr) {
    Renderer* r = asRenderer(rr);
    if (!r) return;
    rendererDestroy(*r);
    delete r;
}

// The T2K screen flash (game/fx_events.h): the core's envelope, mapped for
// this display -- full on a flat screen, attenuated and shortened in VR.
static float flashFor(const Renderer& r, const GameEngine& engine) {
    return r.xrMode ? flash_display_vr(engine.flash, engine.audio_safe_mode)
                    : flash_display(engine.flash, engine.audio_safe_mode);
}

void ts_render_frame(TsRenderer rr, GameEngine& engine) {
    Renderer* r = asRenderer(rr);
    if (!r) return;
    if (!frameBegin(*r, &engine, false)) return;
    drawGameplay(*r, engine);
    const float white[3] = {1.0f, 1.0f, 1.0f};
    frameEnd(*r, flashFor(*r, engine), white);
}

// ---- the PAUSE frame (ui/pause_fx.h) -----------------------------------------
void ts_render_pause_menu_begin(TsRenderer rr) {
    Renderer* r = asRenderer(rr);
    if (!r) return;
    // The overlay text batch lives in CPU pools: the ring only opens at
    // frameBegin, which runs after the caller has emitted the menu's rows.
    // The pools are copied into the ring inside the pause frame.
    if (r->pauseTextFailed) return;
    if (!r->pauseSegBase || !r->pauseTriBase) {
        // All or nothing, and STICKY on failure: a half-allocation would leave
        // one pool null forever (the outer test only looked at the seg pool)
        // and the flush would walk a null base, while an un-sticky failure
        // would retry the same failing new[] on every pause frame -- the
        // per-frame-allocation shape the 3DS batches avoid by the same law.
        if (!r->pauseSegBase) r->pauseSegBase = new (std::nothrow) SegInst[Renderer::PAUSE_TEXT_SEG_MAX];
        if (!r->pauseTriBase) r->pauseTriBase = new (std::nothrow) TriVert[Renderer::PAUSE_TEXT_TRI_MAX];
        if (!r->pauseSegBase || !r->pauseTriBase) { r->pauseTextFailed = true; return; }
    }
    r->pauseSegs = SegStream{};
    r->pauseSegs.base = r->pauseSegBase; r->pauseSegs.cap = Renderer::PAUSE_TEXT_SEG_MAX;
    r->pauseTris = TriStream{};
    r->pauseTris.base = r->pauseTriBase; r->pauseTris.cap = Renderer::PAUSE_TEXT_TRI_MAX;
    fontSetTarget(r, &r->pauseSegs, &r->pauseTris);
}

void ts_render_pause_frame(TsRenderer rr, ts::GameEngine& engine) {
    Renderer* r = asRenderer(rr);
    if (!r) return;
    // Whatever happens, this bracket closes: a frameBegin that fails (a
    // swapchain rebuild) must not leave the staged batch adopting the next
    // live gameplay frame's font emissions.
    fontSetTarget(nullptr, nullptr, nullptr);
    if (!frameBegin(*r, &engine, false)) return;
    // The frozen state with the pause presentation at engine.pause_fx:
    // gameplay melts its surroundings into the chamber; the bonus round just
    // frosts. The overlay text flushes inside the state's own pass.
    if (engine.state == GameState::WARP) drawWarp(*r, engine);
    else                                 drawGameplay(*r, engine);
    const float white[3] = {1.0f, 1.0f, 1.0f};
    frameEnd(*r, flashFor(*r, engine), white);
}

void ts_render_warp(TsRenderer rr, GameEngine& engine) {
    Renderer* r = asRenderer(rr);
    if (!r) return;
    if (!frameBegin(*r, &engine, false)) return;
    drawWarp(*r, engine);
    const float white[3] = {1.0f, 1.0f, 1.0f};
    frameEnd(*r, flashFor(*r, engine), white);
}

void ts_render_fade(TsRenderer rr, float level) {
    Renderer* r = asRenderer(rr);
    if (!r) return;
    if (level < 0.0f) level = 0.0f;
    if (level > 1.0f) level = 1.0f;
    r->fade = level;
}

bool ts_ui_tube_texture(TsRenderer rr, int level) {
    Renderer* r = asRenderer(rr);
    if (!r) return false;
    if (level < 0) { r->uiTubeTexLevel = -1; return false; }
    // Live procedural planes: the UI slot is (re)generated for this set at the
    // next frame's texgen pass; binding is always possible.
    r->uiTubeTexLevel = level;
    return true;
}

bool ts_render_level_ready(TsRenderer rr, int level) {
    (void)rr; (void)level;
    // The skin is generated live every frame: there is never anything to wait
    // for. (A parameter difference from the 3DS, which generates on a worker.)
    return true;
}

// No-op on PC: there is no worker to preheat (see ts_render_level_ready).
// Exists so both frontends call the same entry path -- backend split is by
// file, not ifdef, per the contract.
void ts_prefetch_level_texture(TsRenderer rr, int level) {
    (void)rr; (void)level;
}

// No-op on PC: no deferred SD logs and no worker/staging state to dump
// (the skin is generated live -- see ts_render_level_ready).
void ts_render_diag_level_tex(TsRenderer rr, int level) {
    (void)rr; (void)level;
}

void ts_flush_diag_logs(TsRenderer) {}

void ts_ui_mark_textured_span(TsRenderer rr) {
    Renderer* r = asRenderer(rr);
    if (!r || !r->uiOpen) return;
    r->uiTexturedSpanEnd = r->uiTris.count;
}

void ts_render_ui_begin(TsRenderer rr) {
    Renderer* r = asRenderer(rr);
    if (!r) return;
    if (!frameBegin(*r, nullptr, true)) return;
    // Generate the UI slot's skin for the level the caller will preview.
    if (r->uiTubeTexLevel >= 0)
        texgenRun(*r, r->texgen[1], r->uiTubeTexLevel % GRID_NUM_TEX, (float)r->frameCounter / 60.0f, 0.0f, false);
    uiBegin(*r, UI_CLEAR);
}

void ts_render_ui_end(TsRenderer rr) {
    Renderer* r = asRenderer(rr);
    if (!r || !r->frameOpen) return;
    uiEnd(*r);
    const float white[3] = {1.0f, 1.0f, 1.0f};
    frameEnd(*r, 0.0f, white);
}

void ts_render_title_begin(TsRenderer rr, GameEngine& engine) {
    Renderer* r = asRenderer(rr);
    if (!r) return;
    if (!frameBegin(*r, &engine, true)) return;
    drawTitleLogo(*r, engine);       // opens the scene pass itself (chamber first)
    segStreamBegin(*r, r->uiSegs, 32768);
    triStreamBegin(*r, r->uiTris, 65536);
    r->uiTexturedSpanEnd = -1;
    r->uiOpen = true;
    r->uiTitle = true;
    fontSetTarget(r, &r->uiSegs, &r->uiTris);
}

void ts_render_title_end(TsRenderer rr) {
    Renderer* r = asRenderer(rr);
    if (!r || !r->frameOpen) return;
    uiEnd(*r);
    r->uiTitle = false;
    const float white[3] = {1.0f, 1.0f, 1.0f};
    frameEnd(*r, 0.0f, white);
}

void ts_render_bottom_begin(TsRenderer) {}
void ts_render_bottom_end(TsRenderer) {}

const char* ts_render_backend_name(void) {
    return "Vulkan 1.3";
}
